/**
 * Route definitions — wired in Step 4 with React Router and guards.
 */
export const ROUTES = {
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  onboarding: '/onboarding',
  dashboard: '/dashboard',
  stores: '/stores',
  storeDetail: (id: string) => `/stores/${id}`,
  users: '/users',
  products: '/products',
  inventory: '/inventory',
  sales: '/sales',
  pos: (storeId?: string) => (storeId ? `/stores/${storeId}/pos` : '/pos'),
  purchases: '/purchases',
  customers: '/customers',
  suppliers: '/suppliers',
  transfers: '/transfers',
  cash: '/cash',
  reports: '/reports',
  ai: '/ai',
  settings: '/settings',
  storeIncreaseRequests: '/store-increase-requests',
  createSuperAdmin: '/create-super-admin',
  admin: '/admin',
  adminCompanies: '/admin/companies',
  adminStores: '/admin/stores',
  adminUsers: '/admin/users',
  adminAI: '/admin/ai',
  adminRapports: '/admin/reports',
  adminSettings: '/admin/settings',
  adminStoreRequests: '/admin/store-requests',
  adminAudit: '/admin/audit',
} as const
